import { createSlice } from "@reduxjs/toolkit";

export const propertySlice = createSlice({
  name: "property",
  initialState: {
    data: {
      _id: "65c795ddf4edf337647a1681",
      typesAndPurpose: {
        category: "commercial",
        subCategory: "office",
        purpose: "forRent",
      },
      locationAndAddress: {
        location:
          "Flat302 - Muwaileh Commercial - Industrial Area - Sharjah - United Arab Emirates",
        longitude: 54.407007002975796,
        latitude: 24.43214670001102,
        address: "peoples chowrangi",
      },
      propertyDetails: {
        refNo: "",
        title: "",
        titleArabic: "",
        description: "",
        descriptionArabic: "",
        areaSquare: 0,
        InclusivePrice: 0,
        PermitNumber: 0,
        ownerShipStatus: "",
        bedRooms: 0,
        bathRooms: 0,
      },
      rentalDetails: {
        rent: "500",
        rentFrequency: "monthly",
        minimumContractPeriod: "1",
        noticePeriod: "1",
        maintainanceFee: "200",
        paidBy: "tenant",
      },
      contactDetails: {
        ListingOwner: "",
        contactPerson: "",
        email: "",
        phone: "",
      },
      amenities: [
        {
          name: "Barbeque",
          value: "Barbeque",
          _id: "65c795ddf4edf337647a1682",
        },
        { name: "Care", value: "Care", _id: "65c795ddf4edf337647a1683" },
        {
          name: "Kids Play Area",
          value: "Kids Play Area",
          _id: "65c795ddf4edf337647a1684",
        },
        { name: "Sauna", value: "Sauna", _id: "65c795ddf4edf337647a1685" },
        {
          name: "Swimming Pool",
          value: "Swimming Pool",
          _id: "65c795ddf4edf337647a1686",
        },
        {
          name: "Steam Room",
          value: "Steam Room",
          _id: "65c795ddf4edf337647a1687",
        },
        {
          name: "Laundry Facility",
          value: "Laundry Facility",
          _id: "65c795ddf4edf337647a1688",
        },
        {
          name: "Service Elevator",
          value: "Service Elevator",
          _id: "65c795ddf4edf337647a1689",
        },
        {
          name: "Reception/Waiting room",
          value: "Reception/Waiting room",
          _id: "65c795ddf4edf337647a168a",
        },
        {
          name: "CCTV security",
          value: "CCTV security",
          _id: "65c795ddf4edf337647a168b",
        },
        {
          name: "Waste Disposal",
          value: "Waste Disposal",
          _id: "65c795ddf4edf337647a168c",
        },
        {
          name: "Maintenance Staff",
          value: "Maintenance Staff",
          _id: "65c795ddf4edf337647a168d",
        },
        {
          name: "Cleaning Services",
          value: "Cleaning Services",
          _id: "65c795ddf4edf337647a168e",
        },
        { name: "bedRooms", _id: "65c795ddf4edf337647a168f" },
        { name: "bathRooms", _id: "65c795ddf4edf337647a1690" },
        { name: "completionYear", _id: "65c795ddf4edf337647a1691" },
        {
          name: "elevatorBuilding",
          value: "2",
          _id: "65c795ddf4edf337647a1692",
        },
        { name: "totalFloors", value: "6", _id: "65c795ddf4edf337647a1693" },
        { name: "otherRooms", value: "3", _id: "65c795ddf4edf337647a1694" },
        { name: "mainFeatures", value: "", _id: "65c795ddf4edf337647a1695" },
        { name: "facilities", _id: "65c795ddf4edf337647a1696" },
        { name: "landArea", value: "1", _id: "65c795ddf4edf337647a1697" },
        { name: "nearbySchool", value: "", _id: "65c795ddf4edf337647a1698" },
        {
          name: "nearbyHospitals",
          value: "",
          _id: "65c795ddf4edf337647a1699",
        },
        { name: "nearbyMalls", value: "", _id: "65c795ddf4edf337647a169a" },
        { name: "distance", _id: "65c795ddf4edf337647a169b" },
        {
          name: "nearbyTransport",
          value: "",
          _id: "65c795ddf4edf337647a169c",
        },
        {
          name: "otherNearbyPlaces",
          value: "",
          _id: "65c795ddf4edf337647a169d",
        },
        { name: "parkingSpaces", _id: "65c795ddf4edf337647a169e" },
        { name: "view", value: "", _id: "65c795ddf4edf337647a169f" },
        { name: "floor", _id: "65c795ddf4edf337647a16a0" },
        { name: "petPolicy", value: "", _id: "65c795ddf4edf337647a16a1" },
        { name: "Garden", value: "Garden" },
        { name: "Cafeteria or Canteen", value: "Cafeteria or Canteen" },
        { name: "First Aid Medical Center", value: "First Aid Medical Center" },
        { name: "Jacuzzi", value: "Jacuzzi" },
        { name: "Facilities for Disabled", value: "Facilities for Disabled" },
        { name: "Shared Kitchen", value: "Shared Kitchen" },
        { name: "Balcony or Terrace", value: "Balcony or Terrace" },
        { name: "Lanudry Room", value: "Lanudry Room" },
        { name: "Lobby in Building", value: "Lobby in Building" },
        { name: "Business Center", value: "Business Center" },
        { name: "Conference Room", value: "Conference Room" },
        { name: "Security Staff", value: "Security Staff" },
        { name: "Freehold", value: "Freehold" },
        { name: "Maids Room", value: "Maids Room" },
        { name: "ATM Facility", value: "ATM Facility" },
        { name: "24 Hours Challenge", value: "24 Hours Challenge" },
        { name: "Braodband Internet", value: "Braodband Internet" },
        { name: "Satellite/Cable Tv", value: "Satellite/Cable Tv" },
        { name: "Intercom", value: "Intercom" },
        { name: "Double Glazed Windows", value: "Double Glazed Windows" },
        { name: "Electricity Backup", value: "Electricity Backup" },
        { name: "Central Heating", value: "Central Heating" },
        {
          name: "Centrally Air-Conditioned",
          value: "Centrally Air-Conditioned",
        },
        { name: "Storage Areas", value: "Storage Areas" },
        { name: "Furnished", value: "Furnished" },
        { name: "Study Room", value: "Study Room" },
        { name: "bedRooms", value: "2" },
        { name: "bathRooms", value: "2" },
        { name: "completionYear", value: "6" },
        { name: "elevatorBuilding", value: "4" },
        { name: "totalFloors", value: "2" },
        { name: "otherRooms", value: "3" },
        { name: "mainFeatures", value: "Classrooms" },
        { name: "facilities", value: "Other facilities" },
        { name: "landArea", value: "4" },
        { name: "nearbySchool", value: "Yes" },
        { name: "nearbyHospitals", value: "Yes" },
        { name: "nearbyMalls", value: "Yes" },
        { name: "distance", value: "10" },
        { name: "nearbyTransport", value: "Yes" },
        { name: "otherNearbyPlaces", value: "University" },
        { name: "parkingSpaces", value: "2" },
        { name: "view", value: "5" },
        { name: "floor", value: "2" },
        { name: "petPolicy", value: "" },
      ],
      upload: {
        images: [],
        videos: [],
      },
      isLoading: false,
      isError: false,
      featuredProperties: [],
      ownerId: "65c219469836d496b37d36b5",
    },
  },
  reducers: {
    setPropertyData: (state, action) => {
      console.log("Data provided to store", action.payload);
      state.data = {
        ...state.data,
        ...action.payload,
      };
    },
  },
});

export const { setPropertyData } = propertySlice.actions;

export default propertySlice.reducer;
